# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'creation_popup.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):

    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(908, 462)
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(620, 425, 121, 40))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(770, 425, 121, 40))
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(20, 90, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(20, 40, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(20, 141, 91, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(370, 40, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(370, 90, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(20, 190, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.date_birth = QtWidgets.QDateEdit(Form)
        self.date_birth.setGeometry(QtCore.QRect(190, 189, 141, 21))
        self.date_birth.setObjectName("date_birth")
        self.lineEdit_name = QtWidgets.QLineEdit(Form)
        self.lineEdit_name.setGeometry(QtCore.QRect(120, 40, 211, 20))
        self.lineEdit_name.setObjectName("lineEdit_name")
        self.lineEdit_surname = QtWidgets.QLineEdit(Form)
        self.lineEdit_surname.setGeometry(QtCore.QRect(120, 90, 211, 20))
        self.lineEdit_surname.setObjectName("lineEdit_surname")
        self.lineEdit_patr = QtWidgets.QLineEdit(Form)
        self.lineEdit_patr.setGeometry(QtCore.QRect(120, 140, 211, 20))
        self.lineEdit_patr.setObjectName("lineEdit_patr")
        self.lineEdit_age = QtWidgets.QLineEdit(Form)
        self.lineEdit_age.setGeometry(QtCore.QRect(460, 40, 41, 20))
        self.lineEdit_age.setObjectName("lineEdit_age")
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setGeometry(QtCore.QRect(20, 240, 261, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.lineEdit_north = QtWidgets.QLineEdit(Form)
        self.lineEdit_north.setGeometry(QtCore.QRect(280, 240, 51, 20))
        self.lineEdit_north.setObjectName("lineEdit_north")
        self.label_8 = QtWidgets.QLabel(Form)
        self.label_8.setGeometry(QtCore.QRect(20, 290, 271, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.lineEdit_geliomed = QtWidgets.QLineEdit(Form)
        self.lineEdit_geliomed.setGeometry(QtCore.QRect(280, 290, 51, 20))
        self.lineEdit_geliomed.setObjectName("lineEdit_geliomed")
        self.label_9 = QtWidgets.QLabel(Form)
        self.label_9.setGeometry(QtCore.QRect(370, 140, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.checkBox_obesity = QtWidgets.QCheckBox(Form)
        self.checkBox_obesity.setGeometry(QtCore.QRect(480, 140, 82, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.checkBox_obesity.setFont(font)
        self.checkBox_obesity.setObjectName("checkBox_2")
        self.line = QtWidgets.QFrame(Form)
        self.line.setGeometry(QtCore.QRect(10, 410, 891, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label_10 = QtWidgets.QLabel(Form)
        self.label_10.setGeometry(QtCore.QRect(370, 190, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(Form)
        self.label_11.setGeometry(QtCore.QRect(370, 240, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.lineEdit_weight = QtWidgets.QLineEdit(Form)
        self.lineEdit_weight.setGeometry(QtCore.QRect(430, 190, 71, 20))
        self.lineEdit_weight.setObjectName("lineEdit_weight")
        self.lineEdit_height = QtWidgets.QLineEdit(Form)
        self.lineEdit_height.setGeometry(QtCore.QRect(430, 240, 71, 20))
        self.lineEdit_height.setObjectName("lineEdit_height")
        self.label_12 = QtWidgets.QLabel(Form)
        self.label_12.setGeometry(QtCore.QRect(370, 290, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.lineEdit_imt = QtWidgets.QLineEdit(Form)
        self.lineEdit_imt.setGeometry(QtCore.QRect(430, 290, 71, 20))
        self.lineEdit_imt.setObjectName("lineEdit_imt")
        self.line_2 = QtWidgets.QFrame(Form)
        self.line_2.setGeometry(QtCore.QRect(340, 20, 20, 391))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.label_13 = QtWidgets.QLabel(Form)
        self.label_13.setGeometry(QtCore.QRect(20, 340, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.lineEdit_alco = QtWidgets.QLineEdit(Form)
        self.lineEdit_alco.setGeometry(QtCore.QRect(120, 340, 211, 20))
        self.lineEdit_alco.setObjectName("lineEdit_alco")
        self.label_14 = QtWidgets.QLabel(Form)
        self.label_14.setGeometry(QtCore.QRect(20, 380, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.checkBox_gipo = QtWidgets.QCheckBox(Form)
        self.checkBox_gipo.setGeometry(QtCore.QRect(160, 390, 82, 16))
        self.checkBox_gipo.setObjectName("checkBox_gipo")
        self.line_3 = QtWidgets.QFrame(Form)
        self.line_3.setGeometry(QtCore.QRect(520, 20, 20, 391))
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.lineEdit_mon_point = QtWidgets.QLineEdit(Form)
        self.lineEdit_mon_point.setGeometry(QtCore.QRect(700, 40, 191, 20))
        self.lineEdit_mon_point.setObjectName("lineEdit_mon_point")
        self.label_15 = QtWidgets.QLabel(Form)
        self.label_15.setGeometry(QtCore.QRect(540, 40, 181, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.line_4 = QtWidgets.QFrame(Form)
        self.line_4.setGeometry(QtCore.QRect(10, 370, 891, 20))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.line_5 = QtWidgets.QFrame(Form)
        self.line_5.setGeometry(QtCore.QRect(10, 320, 891, 20))
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.line_6 = QtWidgets.QFrame(Form)
        self.line_6.setGeometry(QtCore.QRect(10, 270, 891, 20))
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.line_7 = QtWidgets.QFrame(Form)
        self.line_7.setGeometry(QtCore.QRect(10, 220, 891, 20))
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.line_8 = QtWidgets.QFrame(Form)
        self.line_8.setGeometry(QtCore.QRect(10, 170, 891, 20))
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.line_9 = QtWidgets.QFrame(Form)
        self.line_9.setGeometry(QtCore.QRect(10, 120, 891, 20))
        self.line_9.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.line_10 = QtWidgets.QFrame(Form)
        self.line_10.setGeometry(QtCore.QRect(10, 70, 891, 20))
        self.line_10.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.line_11 = QtWidgets.QFrame(Form)
        self.line_11.setGeometry(QtCore.QRect(10, 10, 891, 20))
        self.line_11.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_11.setObjectName("line_11")
        self.label_16 = QtWidgets.QLabel(Form)
        self.label_16.setGeometry(QtCore.QRect(540, 90, 181, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.lineEdit_nation = QtWidgets.QLineEdit(Form)
        self.lineEdit_nation.setGeometry(QtCore.QRect(700, 90, 191, 20))
        self.lineEdit_nation.setObjectName("lineEdit_nation")
        self.label_17 = QtWidgets.QLabel(Form)
        self.label_17.setGeometry(QtCore.QRect(540, 140, 181, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.lineEdit_birth_place = QtWidgets.QLineEdit(Form)
        self.lineEdit_birth_place.setGeometry(QtCore.QRect(700, 140, 191, 20))
        self.lineEdit_birth_place.setObjectName("lineEdit_birth_place")
        self.label_18 = QtWidgets.QLabel(Form)
        self.label_18.setGeometry(QtCore.QRect(540, 190, 181, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.lineEdit_smoke = QtWidgets.QLineEdit(Form)
        self.lineEdit_smoke.setGeometry(QtCore.QRect(700, 190, 191, 20))
        self.lineEdit_smoke.setObjectName("lineEdit_smoke")
        self.label_19 = QtWidgets.QLabel(Form)
        self.label_19.setGeometry(QtCore.QRect(540, 240, 191, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(Form)
        self.label_20.setGeometry(QtCore.QRect(540, 290, 201, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.lineEdit_ag = QtWidgets.QLineEdit(Form)
        self.lineEdit_ag.setGeometry(QtCore.QRect(740, 240, 151, 20))
        self.lineEdit_ag.setObjectName("lineEdit_ag")
        self.lineEdit_sss = QtWidgets.QLineEdit(Form)
        self.lineEdit_sss.setGeometry(QtCore.QRect(750, 290, 141, 20))
        self.lineEdit_sss.setObjectName("lineEdit_sss")
        self.radioButton_sex = QtWidgets.QRadioButton(Form)
        self.radioButton_sex.setGeometry(QtCore.QRect(430, 90, 70, 16))
        self.radioButton_sex.setObjectName("radioButton_sex")
        self.radioButton_sex2 = QtWidgets.QRadioButton(Form)
        self.radioButton_sex2.setGeometry(QtCore.QRect(470, 90, 70, 16))
        self.radioButton_sex2.setObjectName("radioButton_sex2")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Добавить Пациента"))
        self.pushButton.setText(_translate("Form", "Добавить"))
        self.pushButton_2.setText(_translate("Form", "Отмена"))
        self.label_2.setText(_translate("Form", "Фамилия:"))
        self.label.setText(_translate("Form", "Имя:"))
        self.radioButton_sex.setText("М")
        self.radioButton_sex2.setText("Ж")
        self.label_3.setText(_translate("Form", "Отчество:"))
        self.label_4.setText(_translate("Form", "Возраст:"))
        self.label_5.setText(_translate("Form", "Пол:"))
        self.label_6.setText(_translate("Form", "Дата рождения:"))
        self.label_7.setText(_translate("Form", "Срок проживания на Севере:"))
        self.label_8.setText(_translate("Form", "Участие в Гелиомеде(кол-во):"))
        self.label_9.setText(_translate("Form", "Ожирение:"))
        self.label_10.setText(_translate("Form", "Вес:"))
        self.label_11.setText(_translate("Form", "Рост:"))
        self.label_12.setText(_translate("Form", "IMT:"))
        self.label_13.setText(_translate("Form", "Алкоголь:"))
        self.label_14.setText(_translate("Form", "Гиподинамия:"))
        self.label_15.setText(_translate("Form", "Точка мониторинга:"))
        self.label_16.setText(_translate("Form", "Национальность:"))
        self.label_17.setText(_translate("Form", "Место рождения:"))
        self.label_18.setText(_translate("Form", "Курение:"))
        self.label_19.setText(_translate("Form", "Наследственность по АГ:"))
        self.label_20.setText(_translate("Form", "Наследственность по ССС:"))
